name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npx jest
